# Generated by Django 2.1.12 on 2019-10-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_indredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indredient',
            new_name='Ingredient',
        ),
    ]
